### PR TITLE
Added JenkinsVariables parameter to methods in JobConfigurer

### PR DESCRIPTION
**Pull request by OlgaMaciaszek**
NOTE: This is a backward-incompatible change.

### CODE REVIEW

**Comment by szpak** [comment]
+1

**Comment by ArturGajowy** [comment]
`JobConfigurer`s are somewhat global and are created where `JenkinsVariables` are easily accessible. Why not pass `JenkinsVariables` to them there, using a constructor / property?

**Comment by ArturGajowy** [comment]
BTW: how is life? :) Anybody going to Geecon? or Devoxx? :)

**Comment by OlgaMaciaszek** [comment]
Hello @ArturGajowy . I'm verifying if it will make sense to do it that way instead. I'm fine. Going to both Geecon and Devoxx :). And how are you?

**Comment by ArturGajowy** [comment]
Fine as well. See you in Kraków! :)

**Comment by OlgaMaciaszek** [comment]
As we need this value while JobDsl is executed and not while the builds are executed, it seems it will not work this way. It also seems to be useful in such cases in the future and we think it's better to modify this now as we still don't have that many users.

**Comment by ArturGajowy** [comment]
Ok I've taken a look at how JobConfigurer's are actually instantiated and they're provided by ProjectTemplate-s. So that would force those ProjectTemplate implementations to have a `jenkinsVariables` field passed to those configurers. So it's not as easy as I suggested in my first comment (sorry :)). In spite of that I think it's sensible to add JenkinsVariables to pre/postConfigure methods.

**Comment by szpak** [comment]
At least we had a chance look through the code and understand this and that :).

**Comment by OlgaMaciaszek** [comment]
That's not really seem to be a problem. I have just modified the Configurers returned by PipelineTemplates. Everything is being built and tests pass, so it should be fine.

**Pull request merged**
